environment:
  matrix:
  - TOXENV: "py35"
  - TOXENV: "py36"

install:
  - echo Installed Pythons
  - dir C:\Python*
  - C:\Python35\python -m pip install tox

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - C:\Python35\python -m tox
