language: python
python:
- '3.5'
- '3.6'
- '3.7'
- 'pypy3.5-5.9.0'
- 'nightly'
dist: xenial
matrix:
  include:
    - os: osx
      sudo: required
      language: generic
      python: 3.7
      env:
      - TRAVIS_PYTHON_VERSION: 3.7
  allow_failures:
    - python: nightly
  fast_finish: true
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages
    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/bin
install: |
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew update;
      brew upgrade python;
      python3 -m pip install --upgrade tox tox-travis
  else
      pip install --upgrade tox tox-travis
  fi
script: tox
